### ISSUE TITLE
Various installation issues

### ISSUE THREAD

**Issue by chrisgrieser** [danielfalk/smart-open.nvim#1]
So first, in the installation instructions, the repo name seems to be wrong: `"nvim-telescope/telescope_smart_open.nvim",` should be `danielfalk/smart-open.nvim`.

Then when I restart nvim, I get this error: 
<img width="50%" alt="Pasted image 2023-01-14 17 28 11" src="https://user-images.githubusercontent.com/73286100/212483320-cd97c749-4212-462b-8634-444b33ed394e.png">

So it looks like `fzy-native` is required, even though the docs state that it's only optional. Well, I tried installing it nonetheless. But then I get this error:
<img width="50%" alt="Pasted image 2023-01-14 17 30 00" src="https://user-images.githubusercontent.com/73286100/212483408-7f8721b3-47f4-46ad-b185-294aeecd8520.png">

and this time, I have no idea how I might fix it myself :(

**Comment by danielfalk** [comment]
Thanks for writing this up.  I'll fix this asap.  Sorry, it's my first plugin for public consumption, but I'll get it straightened out and message back.  Thanks again for your report

**Comment by danielfalk** [comment]
Hello, I pushed up a solution to this, which should also no longer require fzy.  Sorry for the inconvenience.  If you want to try it again, it might be necessary to uninstall/reinstall this plugin, but I think it should be good.

**Comment by danielfalk** [comment]
@chrisgrieser feel free to re-open if you have further issues, but I'm going to close this for now.  Thanks again

**Comment by chrisgrieser** [comment]
thanks, can confirm that it works now!
