### ISSUE TITLE
Pressing enter when there are no results throws an error

### ISSUE THREAD

**Issue by NullVoxPopuli** [danielfalk/smart-open.nvim#14]
Reproduction steps:
1. search for something (that hopefully doesn't exist)
2. see no results
3. press enter anyway
4. see error:
![image](https://user-images.githubusercontent.com/199018/215187054-d64f00f8-2651-409c-8244-a569cc5b53f1.png)

**Comment by danielfalk** [comment]
Thanks for reporting.  I guess I'll just make it close the dialog.  Sound good?

**Comment by NullVoxPopuli** [comment]
yeah, I think that matches what I'd expect / I don't think I'd be surprised by that behavior
