### ISSUE TITLE
Can't search with spaces between search keywords?

### ISSUE THREAD

**Issue by lougreenwood** [danielfalk/smart-open.nvim#15]
If I'm searching for a file which I don't remember the exact name of, I usually enter space separated words which I think are part of the name.

For example, if the file is called `timeline-item-person.ts` I might search for `person item`.

In the standard Telescope find files, this will get a match, however it seems that `smart open` needs me to use the exact word separator which the files use on disk (ie. `-`), for example, neither of the following will find any files for the above mentioned file name: `person item`, `item person`.

Is this expected?

(Also, thanks for the great add-on, love it!)

**Comment by danielfalk** [comment]
It uses fzy (or optionally fzf) to do the matching.  It's outside of the scope of this plugin to implement our own algorithm here, but if there's something I'm doing wrong with respect to plugging in the prompt text, then that's something we could change.

On the other hand if fzy/fzf just work differently in this regard, then we could see if we could add the algorithm that telescope uses as an additional option?

I'd appreciate any input or contributions from others on this one.

**Comment by dtormoen** [comment]
Switching to FZF will probably address this issue. This is the exact case I requested fzf support for

**Comment by lougreenwood** [comment]
@dtormoen Is the FZF support merged, I don't see anything in the README for how to configure it in the way you imply. All I see is that `smart open` can use FZF optionally?

As a side note, I'm using the `Astronvim` distro and that ships with `fzf-native`, so I would assume `smart open` would already be using FZF if it's an optional, automatic opt in?

https://astronvim.github.io/acknowledgements#-plugins-used-in-astronvim

Thanks to both of you for the help & advice here! 😄

**Comment by danielfalk** [comment]
Yeah you configure `match_algorithm = 'fzf'`. If you don't specify anything, it's treated as `match_algorithm = 'fzy'`

It's in the docs here: [https://github.com/danielfalk/smart-open.nvim#configuration](https://github.com/danielfalk/smart-open.nvim#configuration)

**Comment by lougreenwood** [comment]
Cool, thanks @danielfalk, I must have missed that - all working as expected now!

Side question, is it possible to configure using the following format rather than directly in the main telescope setup - I'm not sure it's working?

```lua
require("smart_open").setup {
  match_algorithm = "fzf",
}

require("telescope").load_extension "smart_open"
```

I recently saw [this issue](https://github.com/otavioschwanck/telescope-alternate.nvim/issues/3) for another telescope extension which was also missing the above style of config.

**Comment by danielfalk** [comment]
I'm not sure if there's an example of a plugin that woks that way.  The one cited in the issue doesn't work that way as far as I can tell. Instead, telescope extensions are directed to provide a setup function that _telescope_ is responsible for calling.  I provide that [here](https://github.com/danielfalk/smart-open.nvim/blob/2254f030c4ad5080ea5fb2322655aa7651ea7a87/lua/telescope/_extensions/smart_open.lua#L44). 

I just pushed a change however that should allow you to put it as part of your key mapping if you want to override what's configured in setup.

Example:

```lua
vim.api.nvim_set_keymap("n", "<leader><leader>", "", {
   callback = function ()
      require('telescope').extensions.smart_open.smart_open({ match_algorithm = "fzy" })
   end, 
   noremap = true,
   silent = true
})
```

**Comment by lougreenwood** [comment]
@danielfalk Thanks for your reply - I can't find any other addons which use this setup method, but I have a strong _feeling_ that I've seen and used the plugins which allow this before.

However, `telescope-alternate` certainly does allow that particular method - I'm using it in my config right now, for reference, here's both my telescope & telescope alternate configs.

(The nice thing about this setup method is it decouples telescope config from any addon setup & makes splitting up and managing config for telescope much cleaner).

```lua
actions = require "telescope.actions"
return {
  defaults = {
    mappings = {
      i = {
        ["<CR>"] = actions.select_tab,
        ["<C-b>"] = actions.select_default,
        ["<C-_>"] = actions.select_horizontal,
        ["<C-Bslash>"] = actions.select_vertical,
      },
    },
  },
  extensions = {
    smart_open = {
      match_algorithm = "fzf",
    },
  },
}
```

```lua
require("telescope-alternate").setup {
  layout_strategy = "vertical",
  layout_config = {
    vetical = {},
  },
  mappings = {
    -- .... loads of stuff here
  },
}

require("telescope").load_extension "telescope-alternate"
```

> I just pushed a change however that should allow you to put it as part of your key mapping if you want to override what's configured in setup.

Thanks!

**Comment by danielfalk** [comment]
OK yeah that helps.  I see what they're doing and should be able to make this change

**Comment by danielfalk** [comment]
I've got a new branch for this if you want to try it.  It seems to work for me, but if you want to give it a shot and let me know, the branch is called `alternate-setup`

**Comment by lougreenwood** [comment]
Thanks @danielfalk, I've switched to that branch and it seems to work well!

The only weirdness is the inconsistency with the setup & telescope names (kebab vs snake casing of `smart-open`), but not sure if that's a real problem or not...

```lua
return {
    "danielfalk/smart-open.nvim",
    dependencies = { "kkharji/sqlite.lua" },
    event = "BufRead",
    branch = "alternate-setup",
    config = function()
        require("smart-open").setup {
            match_algorithm = "fzf",
        }
        require("telescope").load_extension "smart_open"
    end,
}
```

See `require("smart-open")` vs `require("telescope").load_extension "smart_open"`

**Comment by lougreenwood** [comment]
I'm also interested in trying out the other fixes in the `0.2` branch. Do you have plans to merge this `alternate-setup` to master and back port to `0.2`?

**Comment by danielfalk** [comment]
OK, it's backported now.

**Comment by lougreenwood** [comment]
Thanks @danielfalk - love the new results in 0.2.x - the `file_name path` colouring is so much better.

I don't suppose you have a snippet to use this same highlighting by default in telescope file pickers? (figured you might have configured your setup to use this everywhere?)
