### ISSUE TITLE
Inconsistent search result keyword highlighting?

### ISSUE THREAD

**Issue by lougreenwood** [danielfalk/smart-open.nvim#16]
Telescope built in find files will highlight all partial matches in the file name, for example if I search `person item` then the search result will have the following highlights (bold used to indicate highlight): `timeline-**item**-**person**`.

However, `smart open` highlight behaves much more erratically, for example, see this screenshot, I see some fragments of the search term highlighted, but not others.

![Screenshot 2023-01-31 at 20 47 35](https://user-images.githubusercontent.com/12051736/215879968-639fc1de-e011-4513-8392-df4875416cd2.png)

**Comment by lougreenwood** [comment]
Actually, taking a closer look at Telescope find files, it seems it also isn't behaving as consistently as I first thought... 🤔 

![Screenshot 2023-01-31 at 20 52 05](https://user-images.githubusercontent.com/12051736/215880616-471bd6c1-f534-4555-9dad-d83b1eefe115.png)

**Comment by marlun** [comment]
I found something similar when using fzf algorithm, if I add a space the highlighting totally disappears, nothing is highlighted.

**Comment by danielfalk** [comment]
This is fixed on the `0.2.x` branch, which is pushed and available, but still needs user feedback before I'd consider it "released".

Anyway, it now highlights differently depending on whether you use fzy or fzf so that it matches what the algorithm is doing.
