### ISSUE TITLE
Use default `TelescopePrompt` filetype

### ISSUE THREAD

**Issue by kuntau** [danielfalk/smart-open.nvim#18]
https://github.com/danielfalk/smart-open.nvim/blob/2254f030c4ad5080ea5fb2322655aa7651ea7a87/lua/telescope/_extensions/smart_open/picker.lua#L66

Any particular reason why this need to be set as `smart_open` filetype? Most extensions have `TelescopePrompt` filetype ignored to prevent weird interactions.

Changing this to other filetype just make more hustle for users to have manually ignore this filetype in other extension. For example [autopairs.nvim](https://github.com/windwp/nvim-autopairs#default-values)

**Comment by danielfalk** [comment]
No, I don't remember why I thought that might be a good idea.  I've updated it.  Thanks for the report.
