### ISSUE TITLE
FZF native support

### ISSUE THREAD

**Issue by dtormoen** [danielfalk/smart-open.nvim#2]
Is it possible to allow use of fzf native (https://github.com/nvim-telescope/telescope-fzf-native.nvim) instead of fzy-native? I used fzf-native this with telescope-frecency.nvim, but smart-open looks promising to address some of the pain points I had with telescope-frecency.

**Comment by danielfalk** [comment]
I don't use it so I'm not sure.  I could look into it though, and I'm willing to take a PR to this effect.  Thanks for the feedback.  Out of curiosity, is fzf better than fzy?

**Comment by dtormoen** [comment]
I mainly like it because it seems a bit more robust to typos :) and it seems find the right thing more often when the word order is wrong. Say you type in "bar foo" when searching for "foobar.py"

**Comment by danielfalk** [comment]
I created an experimental branch that introduces `match_algorithm` as an option.  Set it to `fzf` and it uses fzf instead.  If you're willing to try it, the branch is name `fzf`.  Thanks for the idea.

**Comment by dtormoen** [comment]
Looks like the branch you sent is working great! Thank you! Minor thing, but `show_scores = true` doesn't seem to be working on either branch for me.

**Comment by danielfalk** [comment]
Thanks.  Weird, it does for me.  Although there's too much info in there now and it's just so cryptic I don't know if it would give you much useful info anyway :-(  If I could find a way to make the information more useful and presentable, I'd do that, but as it is, I'm considering doing away with the option altogether.  I'm open to further ideas on that front, and PRs too.  Especially PRs ;-)

**Comment by danielfalk** [comment]
This is now on the main branch.
