### ISSUE TITLE
would using jfind eliminate the constraints on searched files?

### ISSUE THREAD

**Issue by NullVoxPopuli** [danielfalk/smart-open.nvim#22]
Seems very fast: https://www.reddit.com/r/neovim/comments/1446q8o/jfind_over_130x_faster_than_telescope_while_using/

The main thing i'm looking for:
 - within the cwd, always search all files, (respecting ignores, ofc, don't need to look in node_modules)

**Comment by danielfalk** [comment]
I'd like to look into this at some point.  When it comes to search, there is probably always going to be some tradeoff between sheer performance of an algorithm and its power.  (I'm defining "power" here as the ability to give you the best relevance, even with incomplete information.  "Fuzziness" in other words.)

I've been impressed with fzf's algorithm though.  I'm glad that someone suggested including it in smart-open, and that's the algorithm I use now.

Have you been able to try `0.2.x` again now that the issues you noticed have been addressed?   It should have improved performance and there is no longer a limit on the number of files that can be searched.

**Comment by danielfalk** [comment]
The jfind.nvim plugin uses [jfind](https://github.com/jake-stewart/jfind), which claims to be faster version of fzf.  Maybe this can be pulled in as an additional match algorithm.  I'm not sure yet.  There's not a lot of documentation to it.

**Comment by NullVoxPopuli** [comment]
> Have you been able to try 0.2.x again

I thought I was, but on my new work computer, apparently I was using the old version!
gonna give this a couple days of usage and see how it feels.

**Comment by NullVoxPopuli** [comment]
I found an issue, I _really_ need the search to be contained to the `cwd`. searching outside of the `cwd` has _only_ caused problems for me 😢 

![image](https://github.com/danielfalk/smart-open.nvim/assets/199018/83259a4e-8c63-4624-b88e-733021d433dd)

on the main branch, 
this was enough to keep the search scoped to the cwd
```vim
nnoremap <C-t> :lua require('telescope').extensions.smart_open.smart_open({cwd_only = true})<CR>
```
is there a way to regain this narrowing of scope?

**Comment by danielfalk** [comment]
@NullVoxPopuli Opened a new bug, #25
