### ISSUE TITLE
cwd_only including items outside working directory

### ISSUE THREAD

**Issue by danielfalk** [danielfalk/smart-open.nvim#25]
I found an issue, I _really_ need the search to be contained to the `cwd`. searching outside of the `cwd` has _only_ caused problems for me 😢 

![image](https://github.com/danielfalk/smart-open.nvim/assets/199018/83259a4e-8c63-4624-b88e-733021d433dd)

on the main branch, 
this was enough to keep the search scoped to the cwd
```vim
nnoremap <C-t> :lua require('telescope').extensions.smart_open.smart_open({cwd_only = true})<CR>
```
is there a way to regain this narrowing of scope?

_Originally posted by @NullVoxPopuli in https://github.com/danielfalk/smart-open.nvim/issues/22#issuecomment-1585073882_

**Comment by danielfalk** [comment]
I have tested this quite a bit and it mostly seems to work, but I did notice one instance where the path of a previously-edited file had the working directory somewhere in its full path, though the full path _didn't start with_ the working directory path.  I'll push that fix as soon as I test it a bit more.  @NullVoxPopuli you don't mention the the working directory, so I'm not sure if this is the cause of your issue.

**Comment by NullVoxPopuli** [comment]
I usually notice it with git worktrees, so my setup is like this:

```
~/Development/NullVoxPopuli/
  original clone
  worktree-1
  worktree-2
  worktree-3
  worktree-4
```
and all of those are monorepos, so when I search for package.json, and I _have_ recently opened the packaeg.json in all of those worktrees, it seems to show the results from each worktree -- which I don't want. Like, it's not useful information to show me recently opened files outside my current working directory, which is almost always a git root (or worktree root)

**Comment by danielfalk** [comment]
I've pushed the fix.  I don't know if it will solve the entire issue based upon what you're describing, so I'll keep diving into it.

**Comment by NullVoxPopuli** [comment]
thanks! I'll update right now and see if I notice any issues throughout the day

**Comment by danielfalk** [comment]
I think I got it finally.  Try updating once more.  Sorry for the annoyance this must have caused you!

**Comment by NullVoxPopuli** [comment]
oh no worries, thanks for being an active maintainer!!! <3 :tada: 
Active maintainers are so rare these days, it seems :upside_down_face:

**Comment by danielfalk** [comment]
If this works for you, it should have also been a problem with `0.1.x` though.  I'm backporting these fixes to that branch as well.

**Comment by NullVoxPopuli** [comment]
I had no issues at all today! thanks a ton!!
