### ISSUE TITLE
nvim cmp is trying to suggest things when I'm searching

### ISSUE THREAD

**Issue by NullVoxPopuli** [danielfalk/smart-open.nvim#29]
I know this isn't exactly related to smart-open.nvim, as this problem can occur in any input,
but is there documentation somewhere for disabling cmp in everything except the main code buffers?

**Comment by danielfalk** [comment]
I'm no cmp expert by any means, but I found this issue: [https://github.com/hrsh7th/nvim-cmp/issues/60](https://github.com/hrsh7th/nvim-cmp/issues/60)

It says that any prompts that have a buftype of 'prompt' should be exempted from autocomplete popups.  This is handled by telescope, which does set the type to `prompt` as it should, so I think it might be something with your configuration somehow but I'm not sure.  Hopefully that points you in the right direction.
