### ISSUE TITLE
Simpler mapping

### ISSUE THREAD

**Issue by YodaEmbedding** [danielfalk/smart-open.nvim#36]
[Regarding the README](https://github.com/danielfalk/smart-open.nvim#usage), a simpler mapping exists:

```lua
vim.keymap.set("n", "<leader><leader>", require("telescope").extensions.smart_open.smart_open)
```

**Comment by danielfalk** [comment]
Interesting.  I tried this just now and it didn't work.  I think it's because where my keymappings are defined, the plugin maybe isn't loaded yet.  Doing this does work:
```lua
vim.keymap.set("n", "<leader><leader>", function ()
  require("telescope").extensions.smart_open.smart_open()
end)
```
