### ISSUE TITLE
[Question] how to exclude directories from suggestions?

### ISSUE THREAD

**Issue by obayit** [danielfalk/smart-open.nvim#4]
I open the project i am working on by using `cd ~/path/to/project` then  `vi .`
Is there a way to exclude directories from being used?

![Screenshot from 2023-01-15 14-10-29](https://user-images.githubusercontent.com/20386024/212540102-e9d520ed-3e8d-462d-90a3-34429c0cadf7.png)

**Comment by danielfalk** [comment]
Hmm.  That's a bug.  Directories shouldn't be included.  Thanks for the report.

**Comment by danielfalk** [comment]
For some reason I was unable to reproduce this one myself.  I think there might be some difference in configuration in how your setup handles opening directories from how mine does, but I put in a fix that should prevent future directories from getting saved in the db.  Unfortunately once it's in there, you will probably continue to see it in the search results for a while :-(

The easiest way to get rid of it is to delete `~/.local/share/nvim/smart_open.sqlite3` (or wherever your nvim data dir is...) and the entry won't come back.  Also, you could just open the db and do a `DELETE FROM files WHERE ... ` on it.  At some point I'd like to create a db cleanup command but for now I hope this will suffice.

Also, if you continue to see new directories getting added to the history, feel free to reopen this.
