### ISSUE TITLE
Latest combination of things has no (visilbe) files listed in results view

### ISSUE THREAD

**Issue by NullVoxPopuli** [danielfalk/smart-open.nvim#42]
![image](https://github.com/danielfalk/smart-open.nvim/assets/199018/75a36145-bc0a-4b13-83b2-8045c4c0817d)
Searching for anything shows no results, but if I use the up/down keys, I can see the preview change when I have enough space for the preview to fit.

Looks like it's this issue: https://github.com/nvim-telescope/telescope.nvim/issues/2667
Which is solved here: https://github.com/nvim-telescope/telescope.nvim/pull/2679

(not a smart-open.nvim issue)

**Comment by AdamSitar** [comment]
Hi @NullVoxPopuli, was this fixed? I'm having this issue
