### ISSUE TITLE
Doesn't find history files outside working directory

### ISSUE THREAD

**Issue by hanspinckaers** [danielfalk/smart-open.nvim#50]
Is it possible to also add historical files independent from the working directory?

Thanks!

**Comment by danielfalk** [comment]
It already works this way, however file matches in your working directory get a bit of a scoring boost.  How much of a boost they receive depends on your usage.

**Comment by hanspinckaers** [comment]
For me it doesn't seem to show files outside sadly:

smart-open.nvim:
<img width="677" alt="Screenshot 2023-11-24 at 09 41 47" src="https://github.com/danielfalk/smart-open.nvim/assets/70747/c88437b9-d136-417b-921c-263add794500">

oldfiles Telescope:
![compare](https://github.com/danielfalk/smart-open.nvim/assets/70747/851ee6d9-16e0-4d71-85fa-4d8fd372a577)

**Comment by danielfalk** [comment]
If `pwd` is different, do the files show up in smart_open?  Are you using the `cwd_only` setting?

**Comment by hanspinckaers** [comment]
You're correct, my cwd_only was set to true 😅

Thanks for the awesome extension!
