### ISSUE TITLE
[feature request] ctrl-c to close telescope prompt

### ISSUE THREAD

**Issue by zhengpd** [danielfalk/smart-open.nvim#62]
I'd like to close the telescope prompt with `C-c`, which is the default behavior of Telescope. It would be nice if there could be an option to disable the `C-c` mapping in smart-open.nvim.

**Comment by danielfalk** [comment]
Hi, what branch are you on?  The `0.2.x` branch should have addressed this

**Comment by zhengpd** [comment]
@danielfalk Thank you. `0.2.x` works. I was on `main` branch. I thought `main` contain latest changes.
