### ISSUE TITLE
Some configuration and mapping are broken in `main` branch

### ISSUE THREAD

**Issue by Parsifa1** [danielfalk/smart-open.nvim#75]
Compared with `0.2.x`, `<C-c>` on main seems to be damaged, unable to perform the `close` function, and cannot pass
```lua
smart_open = {
            match_algorithm = "fzf",
            mappings = {
                ["<C-c>"] = "close",
            },
        },
```
to set

**Comment by danielfalk** [comment]
This should work now.  Main has been updated.  Feel free to re-open if the issue is still there.
