### ISSUE TITLE
add it to luarocks.org ? 

### ISSUE THREAD

**Issue by teto** [danielfalk/smart-open.nvim#78]
hi,

thanks for writing this plugin. I've long dreamt about it and you made it ! 

It depends on several plugins  https://github.com/danielfalk/smart-open.nvim?tab=readme-ov-file#requirements and as such is a perfect candidate for a luarocks package, which recent plugin managers such as  https://github.com/nvim-neorocks/rocks.nvim or https://github.com/folke/lazy.nvim can leverage to autoinstall dependencies.
Also since you've already have 0.1 and 0.2 branches, looks like you care about versioning.

See https://github.com/nvim-neorocks/rocks.nvim/wiki/Plugin-support how to do this and let me know if you want help.

**Comment by teto** [comment]
I've added it: https://luarocks.org/modules/neorocks/smart-open.nvim but now I have:

> Unable to find native fzy native lua dep file. Probably need to update submodules! 

even though the README marks the dependency as optional. I dont mind either way but if it's optional, the plugin should not display this distracting warning.

**Comment by danielfalk** [comment]
Thanks for doing this!  Let me see if I can look into the warning.
