### ISSUE TITLE
Can the configuration take the cwd_only option?

### ISSUE THREAD

**Issue by NullVoxPopuli** [danielfalk/smart-open.nvim#8]
atm, it seems cwd_only can only be set via 
```lua
require('telescope').extensions.smart_open.smart_open({cwd_only = true})
```
but because of issue: https://github.com/danielfalk/smart-open.nvim/issues/7
I'd like to set cwd_only to true in the telescope configuration:
https://github.com/danielfalk/smart-open.nvim#example-configuration

**Comment by danielfalk** [comment]
Closing this, since #7 was fixed.  I'll take a PR on it if anybody's interested in contributing this.
