### ISSUE TITLE
[Feature Request]  Add search inside files (Aka live_grep)

### ISSUE THREAD

**Issue by barcell1** [danielfalk/smart-open.nvim#89]
This would make this plugin the only that i need for search if this feature  be implemented 

Great plugin so far ! Congrats !

**Comment by danielfalk** [comment]
Thanks!

I think if I added that it would have to be a separate keybind, or the results would arrive too slowly, and be flooded with more results, making it difficult to wade through. 

If it's a separate keybind, there are other plugins that do this anyway, so it would just be a reimplementation of already existing things.  Sorry, I just can't think of a way to add this that would be contributing anything unique.

**Comment by barcell1** [comment]
`I think if I added that it would have to be a separate keybind, or the results would arrive too slowly, and be flooded with more results, making it difficult to wade through.`

I was thinking in a way to have a universal grep, that could do a live_grep or file name grep and using all the smartness of this plugin to rate the files. 

You could do a pagination (adding a letter to paginate), since your plugin already pick the right files (like 10 files each time, i think paginating would solve the slow problem about the implementation of a universal grep)

**Comment by barcell1** [comment]
`I think one of the issues would be that live_grep decides the file order when searching. Consequently, it's going to show the first matched files, first. That makes sense because it's not going to wait until all the files are matched to start sorting. So I think you'd have to provide a list of pre-ordered files for live_grep to search.`

maybe if live_grep have issues with this implementation, a possibility in the future could be port to fzf lua plugin, i think it dosnt have these constraints.
