### ISSUE TITLE
Extension failing to load on linux

### ISSUE THREAD

**Issue by rbhanot4739** [danielfalk/smart-open.nvim#90]
Hello, 

The extension is failing to load on linux, while the installation for the extension and all its dependencies did went through the config loading fails with the following error.

```
  Error  11:57:40 notify.error lazy.nvim Failed to run `config` for smart-open.nvim

...ot/.local/share/nvim/lazy/sqlite.lua/lua/sqlite/defs.lua:57: libz.so.1: cannot open shared object file: No such file or directory

# stacktrace:
  - /sqlite.lua/lua/sqlite/defs.lua:57
  - /sqlite.lua/lua/sqlite/utils.lua:252 _in_ **__index**
  - /sqlite.lua/lua/sqlite/db.lua:667
  - /sqlite.lua/lua/sqlite/init.lua:66 _in_ **__index**
  - /smart-open.nvim/lua/telescope/_extensions/smart_open/dbclient.lua:28 _in_ **new**
  - /smart-open.nvim/lua/smart-open/init.lua:29 _in_ **setup**
  - /telescope.nvim/lua/telescope/_extensions/init.lua:64 _in_ **load_extension**
  - util-plugins.lua:8 _in_ **config**
  - ~/.config/nvim/lua/config/lazy.lua:18
  - ~/.config/nvim/init.lua:3
  ``` 

I have all the dependencies mentioned in the readme installed and available in the path. I could not find any errors in the `checkhealth` output as well. I did try to install `libz` explicitly but still getting the same error.

**Comment by rbhanot4739** [comment]
Can anyone please update on this ?

**Comment by danielfalk** [comment]
Unfortunately I don't experience this on linux.  It appears to be sqlite.lua problem though.  Maybe [this closed issue](https://github.com/kkharji/sqlite.lua/issues/28) is relevant to your issue?

**Comment by rbhanot4739** [comment]
Sure, I also think so.. I am closing this, will open the issue in sqlite.lua repo.
