### ISSUE TITLE
[Question] cant make ignore_patterns to work, what im doing wrong ?

### ISSUE THREAD

**Issue by barcell1** [danielfalk/smart-open.nvim#92]
part of my telescope config :

 config = function()
    local telescope = require("telescope")
    local actions = require("telescope.actions")

   telescope.setup {
   extensions={
   smart_open = {
      match_algorithm = "fzf",
      disable_devicons = false,
      cwd = '~/',
      ignore_patterns = ignore_files,  
    },
   },

...

local ignore_files = { "assets/", "Excalidraw/" , ".local/" , ".cache/"}

...

**Comment by danielfalk** [comment]
That should work.  Only think I can think of is that the `ignore_files` variable you have doesn't get assigned until after the setup gets called, effectively passing `nil` into `ignore_patterns`. 

also, keep in mind that setting `ignore_files` overwrites the default patterns, which you can find in `lua/telescope/_extensions/smart_open/default_config.lua`.  The default patterns filter out a lot of unhelpful items.
